In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "1": [200, 140, 170, 145, 165],
    "2": [190, 150, 210, 150, 150],
    "3": [230, 190, 200, 190, 200],
    "4": [150, 170, 150, 170, 180]
})
df

     1    2    3    4
0  200  190  230  150
1  140  150  190  170
2  170  210  200  150
3  145  150  190  170
4  165  150  200  180

In [3]:
df_mean = df.mean()
df_mean

1    164.0
2    170.0
3    202.0
4    164.0
dtype: float64

In [4]:
df_var = df.var()
df_var

1    567.5
2    800.0
3    270.0
4    180.0
dtype: float64

In [5]:
x_mean = df_mean.mean()
x_mean

np.float64(175.0)

In [ ]:
D_megh = 5 * sum((df_mean - x_mean) ** 2)
D_megh

4980.0

In [12]:
D_vn = sum(df_var * 5) / 20
D_vn

454.375

# 2

In [13]:
df = pd.DataFrame({
    "A": [30, 100, 300],
    "B_1": [
        [530, 540, 550],
        [490, 510, 520],
        [420, 420, 450]
    ],
    "B_2": [
        [600, 620, 580],
        [550, 540, 560],
        [470, 460, 430]
    ]
})
df

     A              B_1              B_2
0   30  [530, 540, 550]  [600, 620, 580]
1  100  [490, 510, 520]  [550, 540, 560]
2  300  [420, 420, 450]  [470, 460, 430]

In [ ]:
df_mean_A_1_B_1 = sum(df)

TypeError: Could not convert [list([530, 540, 550, 490, 510, 520, 420, 420, 450])
 list([600, 620, 580, 550, 540, 560, 470, 460, 430])] to numeric